FROM node:20 AS build

WORKDIR /app

#라이브러리 설치에 필요한 파일만 복사
COPY package.json .
COPY package-lock.json .

#라이브러리 설치
RUN npm ci

COPY . /app

RUN npm run build

FROM nginx:1.27.1-alpine

COPY nginx.local.conf /etc/nginx/conf.d/default.conf

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80
ENTRYPOINT ["nginx"]
CMD ["-g", "daemon off;"]