version: '3.8'

services:
  dailog-mysql:
    build: .
    container_name: mysql-db
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-1234}
      - MYSQL_DATABASE=dailog
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-mypassword}
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
#    deploy:
#      resources:
#        limits:
#          cpus: '1'
#          memory: 256M
    restart: always

  dailog-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile-local
      args:
        - JASYPT_ENCRYPTOR_PASSWORD=${JASYPT_ENCRYPTOR_PASSWORD}
    environment:
      - DB_URL=dailog-mysql
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-local}
      - JASYPT_ENCRYPTOR_PASSWORD=${JASYPT_ENCRYPTOR_PASSWORD}
    ports:
      - 8080:8080
      - 5005:5005
    depends_on:
      - dailog-mysql
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: 512M
    restart: on-failure

  dailog-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile-local
    ports:
      - 80:80
    depends_on:
      - dailog-backend
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 64M
    restart: on-failure

volumes:
  db_data: