version: '3.8'

services:
  dailog-mysql:
    image: ${DOCKERHUB_USERNAME}/dailog-mysql
    pull_policy: always
    container_name: mysql-db
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-1234}
      - MYSQL_DATABASE=dailog
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-mypassword}
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    #    deploy:
    #      resources:
    #        limits:
    #          cpus: '1'
    #          memory: 256M
    restart: always

  dailog-backend:
    image: ${DOCKERHUB_USERNAME}/dailog-backend
    pull_policy: always
    environment:
      - DB_URL=dailog-mysql
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-local}
      - JASYPT_ENCRYPTOR_PASSWORD=${JASYPT_ENCRYPTOR_PASSWORD}
    depends_on:
      - dailog-mysql
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: 512M
    restart: on-failure

  dailog-frontend:
    image: ${DOCKERHUB_USERNAME}/dailog-frontend
    pull_policy: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./certbot/conf:/etc/letsencrypt  # SSL 인증서 저장소
      - ./certbot/www:/var/www/certbot  # 인증서 발급을 위한 웹 루트 경로
    depends_on:
      - dailog-backend
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 64M
    restart: on-failure

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt  # 인증서 저장소
      - ./certbot/www:/var/www/certbot  # 인증서 발급용 경로
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 12h & wait $${!}; certbot renew; done;'"

volumes:
  db_data: