version: '3.8'

services:
  dailog-mysql:
    image: ${DOCKERHUB_USERNAME}/dailog-mysql
    pull_policy: always
    container_name: mysql-db
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=dailog
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    #    deploy:
    #      resources:
    #        limits:
    #          cpus: '1'
    #          memory: 256M
    restart: always

  cache-server:
    container_name: redis
    image: redis:alpine
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command:
      - /bin/sh
      - -c
      - redis-server --requirepass "$${REDIS_PASSWORD:?REDIS_PASSWORD variable is not set}"
    ports:
      - "6379:6379"

  dailog-backend:
    container_name: backend
    image: ${DOCKERHUB_USERNAME}/dailog-backend
    pull_policy: always
    environment:
      - DB_URL=dailog-mysql
      - REDIS_HOST=cache-server
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - JASYPT_ENCRYPTOR_PASSWORD=${JASYPT_ENCRYPTOR_PASSWORD}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    depends_on:
      - cache-server
      - dailog-mysql
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: 512M
    restart: on-failure

  dailog-frontend:
    container_name: frontend
    image: ${DOCKERHUB_USERNAME}/dailog-frontend
    pull_policy: always
    ports:
      - 80:80
      - 443:443
    depends_on:
      - dailog-backend
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 64M
    restart: on-failure

volumes:
  db_data: