FROM gradle:8.8-jdk17 AS build

# Redis 설치
RUN apt-get update && \
    apt-get install -y redis-server && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

#소스코드를 복사할 작업 디렉토리를 생성
WORKDIR /app

#라이브러리 설치에 필요한 파일만 복사
COPY build.gradle settings.gradle ./
RUN gradle dependencies --no-daemon

COPY . /app

# Redis 서버를 백그라운드에서 실행
# 테스트 실행
ARG JASYPT_ENCRYPTOR_PASSWORD
RUN redis-server --daemonize yes && \
    gradle test \
    -Dspring.profiles.active=test \
    -Djasypt.encryptor.password=${JASYPT_ENCRYPTOR_PASSWORD} && \
    redis-cli shutdown

# 빌드 실행 (테스트 제외)
RUN gradle clean build --no-daemon -x asciidoctor -x test

FROM openjdk:17-jdk-slim

WORKDIR /app
COPY --from=build /app/build/libs/*.jar /app/dailog.jar

EXPOSE 8080
EXPOSE 5005
ENTRYPOINT ["java"]
CMD ["-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005", "-jar", "dailog.jar", "--spring.profiles.active=local"]