name: Deploy to EC2

on:
#  workflow_run:
#    workflows:
#      - MySQL Build and Push
#      - Backend Build and Push
#      - Frontend Build and Push
#    types:
#      - completed
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

#      - name: Start SSH Agent and Add Key
#        run: |
#          echo "${{ secrets.AWS_SSH_PRIVATE_KEY }}" > private_key
#          chmod 600 private_key
#          eval $(ssh-agent -s)
#          echo "${{ secrets.AWS_SSH_PASSPHRASE }}" | ssh-add private_key

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          # GitHub Secret에서 Docker Hub 사용자 이름을 가져옵니다.
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          # GitHub Secret에서 Docker Hub 액세스 토큰을 가져옵니다.

      - name: Copy docker-compose.yml to EC2
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.AWS_SSH_PASSPHRASE }}
          source: docker-compose.yml
          target: /home/ec2-user/

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.AWS_SSH_PASSPHRASE }}
          port: 22
          script: |
            export SPRING_PROFILES_ACTIVE=prod
            export MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}
            export MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}
            export DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}
            export JASYPT_ENCRYPTOR_PASSWORD=${{ secrets.JASYPT_ENCRYPTOR_PASSWORD }}
            
            docker-compose down
            docker-compose up -d